num1 = input('Enter first number:')
num2 = input('Enter second number:')
addition = float(num1)+float(num2)
subtraction = float(num1)-float(num2)
multiplication = float(num1)*float(num2)
division = float(num1)/float(num2)
print('The sum of {0} and {1} is {2}'.format(num1,num2,addition))
print('The subtraction of {0} and {1} is {2}'.format(num1,num2,subtraction))
print('The multiplication of {0} and {1} is {2}'.format(num1,num2,multiplication))
print('The division of {0} and {1} is {2}'.format(num1,num2,division))